POST https://overpass.kumi.systems/api/interpreter HTTP/1.1
Host: overpass.kumi.systems
Connection: keep-alive
Content-Length: 183
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Content-type: application/x-www-form-urlencoded; charset=UTF-8
Accept: */*
Origin: https://anvaka.github.io
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://anvaka.github.io/city-roads/?q=%E6%88%90%E9%83%BD
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,la;q=0.7,it;q=0.6

data=%5Btimeout%3A900%5D%5Bmaxsize%3A1073741824%5D%5Bout%3Ajson%5D%3B%0Aarea(3602110264)%3B%0A(._%3B%20)-%3E.area%3B%0A(way%5Bhighway=%22trunk%22%5D(area.area)%3B%20node(w)%3B)%3B%0Aout%20skel%3B